### ISSUE TITLE
Finishing touches checklist for qView 4.0

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#353]
- [x] Test performance
- [x] Finish up image formats in CI
- [x] Polish up CI builds in general
- [x] General bug testing
- [x] Memory leak test
- [x] tidy and clazy if i feel like it i guess
- [x] Don't forget appimage version in ci
- [x] Ensure updating checking is working on all builds (yes, i mean you, windows)
- [x] Fix qView on older versions of macOS
- [x] application modal dialogs dont seem to be working properly on mac?
- [x] Fix full size content view dying on fullscreen QTBUG-69975
- [x] Recheck dialog modality on linux and windows with new changes
- [x] Investigate #261 
- [x] Look into #251
- [x] Investigate #360 
- [x] Add new supported file types to .desktop, plist, installer, etc
- [x] Update inno setup
- [x] Fix windows copyright encoding for the millionth time
- [x] Legacy os x build cause why not
- [x] Incorrect image size reporting sometimes when loading gif for first time(?)
- [x] add legacy os x build to website
- [x] Add notice of msvc requirement on windows download page (remember its vcruntime140_1 now, so 2015-2019 download)
- [x] Build webpage explaining image formats

**Comment by smarquespt** [comment]
Any chance to allow translations?

**Comment by jurplel** [comment]
@smarquespt I am really excited to add translations and I will have a system set up after 4.0's release
relevant issue: #252

**Comment by smarquespt** [comment]
Great. Thanks

**Comment by Cellane** [comment]
@jurplel I’m sorry to be a bother but do you think that a fix for #261 will make it into the 4.0 release in the end? Thank you 🙇‍♂️

**Comment by jurplel** [comment]
Undecided but I'm going to get into it and see if I can do it without too much hassle before release.

**Comment by BloodRaven0** [comment]
4.0 Hypeee :D
